### ISSUE TITLE
csiro_bgc.res.nc and *_init_*.nc contain salt in addition to BGC variable

### ISSUE THREAD

**Issue by aekiss** [hakaseh/input_om2-bgc#8]
`interpolate_to_access-om2.ipynb` creates `*_init_*.nc` files that contain `salt` in addition to the intended BGC variable. 

`salt` is not used, so this is confusing and a waste of storage.

**Comment by aekiss** [comment]
`salt` is also put in the input file `csiro_bgc.res.nc` actually used by MOM and should be removed.

**Comment by hakaseh** [comment]
Thanks Andrew for checking. I think it's there because I used the salt file as a base model for generating initial BGC files. I can edit the script to fix this if you have not done yet.

Also should we create the updated bgc init file after the o2 bug fix? Paul will need it for his 025 RYF run I think.


Regards,
Hakase
________________________________

**Comment by aekiss** [comment]
Thanks, it would be great if you can fix this issue, then I'll run the script to create new input files.

**Comment by aekiss** [comment]
On second thoughts, I'll fix it

**Comment by hakaseh** [comment]
Thanks Andrew! Been super busy with the moving so this is much appreciated ☺️

Regards,
Hakase
________________________________

**Comment by aekiss** [comment]
This bug has been fixed in `/g/data/ik11/inputs/access-om2/input_bgc_20220224`.
